steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/dispatcher/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/reminder-dispatcher:latest
      - .
images:
  - gcr.io/$PROJECT_ID/reminder-dispatcher:latest
options:
  logging: CLOUD_LOGGING_ONLY
