steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/api/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/reminder-api:latest
      - .
images:
  - gcr.io/$PROJECT_ID/reminder-api:latest
options:
  logging: CLOUD_LOGGING_ONLY
